  # uses: FinalBuild-Studio/swagger-codegen-action@908337d287b51f0a71bef2adb8da5b25497b49e8
  uses: FinalBuild-Studio/swagger-codegen-action@v1.2
  with:
    # Swagger language
    language: rust
    # Swagger file
    input: https://www.torn.com/swagger/openapi.json
    # swagger-codegen-cli action
    action: generate
          
