name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:
  swagger_codegen:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Ensure you fetch all history to avoid shallow clones
          fetch-depth: 0
      
      # Step 2: Generate Client Library using OpenAPI Tools
      - name: Generate Client Library w/ the OpenAPITools Generator
        uses: openapi-generators/openapitools-generator-action@v1.5.0
        with:
          generator: rust
      
      # Step 3: Commit and push changes
      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }} # Use the token from secrets
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-generated code using Swagger Codegen"
          git push https://$GH_PAT@github.com/${{ github.repository }} HEAD:main
